name: Integration Build & Deploy

on:
  push:
    branches: [master]

jobs:

  build:
    name: Build artifacts
    
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@master
    
    - name: Cache node_modules
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    
    - uses: actions/cache@master
      id: yarn-cache
      with:
        path: ${{steps.yarn-cache-dir-path.outputs.dir}}
        key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
        restore-keys: ${{runner.os}}-yarn-
    
    - name: Restore node_modules
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build --prod

    - name: scp to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "dist/ng-vendors"
        strip_components: 2
        target: ${{ secrets.TARGET_PATH }}
        rm: true
